version: '3.6'
networks:
  consul:
  infra:
    external: true
#volumes:
#  consul-1-data:
#  consul-2-data:
#  consul-3-data:
services:
  consul-1:
    image: consul:1.4.3
    networks:
      - consul
    env_file:
      - consul.env
    #    volumes:
    #      - consul-1-data:/consul/data
    deploy:
      placement:
        constraints:
          - "node.hostname == $NODE1"
    command: "agent -server -bootstrap-expect 3 -client 0.0.0.0"
  consul-2:
    image: consul:1.4.3
    networks:
      - consul
    env_file:
      - consul.env
    #    volumes:
    #      - consul-2-data:/consul/data
    deploy:
      placement:
        constraints:
          - "node.hostname == $NODE2"
    command: "agent -server -retry-join consul-1 -client 0.0.0.0"
  consul-3:
    image: consul:1.4.3
    networks:
      - consul
    env_file:
      - consul.env
    #    volumes:
    #      - consul-3-data:/consul/data
    deploy:
      placement:
        constraints:
          - "node.hostname == $NODE3"
    command: "agent -server -retry-join consul-1 -client 0.0.0.0"
  consul:
    image: consul:1.4.3
    networks:
      - consul
      - infra
    env_file:
      - consul.env
    ports:
      - 8500:8500
      - 8600:8600/tcp
      - 8600:8600/udp
    deploy:
      mode: global
    command: "agent -ui -retry-join consul-1 -client 0.0.0.0"