version: '3.6'
networks:
  infra:
    external: true
#volumes:
#  rabbitmq-1-data:
#  rabbitmq-2-data:
#  rabbitmq-3-data:
services:
  rabbitmq-1:
    image: lysakaleksey/rabbitmq:3.7-management-alpine
    hostname: rabbitmq-1
    networks:
      - infra
    env_file:
      - rabbitmq.env
    #    volumes:
    #      - rabbitmq-1-data:/var/lib/rabbitmq
    deploy:
      placement:
        constraints:
          - "node.hostname == $NODE1"
  rabbitmq-2:
    image: lysakaleksey/rabbitmq:3.7-management-alpine
    hostname: rabbitmq-2
    networks:
      - infra
    env_file:
      - rabbitmq.env
    #    volumes:
    #      - rabbitmq-2-data:/var/lib/rabbitmq
    deploy:
      placement:
        constraints:
          - "node.hostname == $NODE2"
  rabbitmq-3:
    image: lysakaleksey/rabbitmq:3.7-management-alpine
    hostname: rabbitmq-3
    networks:
      - infra
    env_file:
      - rabbitmq.env
    #    volumes:
    #      - rabbitmq-3-data:/var/lib/rabbitmq
    deploy:
      placement:
        constraints:
          - "node.hostname == $NODE3"
  rabbitmq:
    image: lysakaleksey/haproxy-for-rabbitmq:1.9-alpine
    deploy:
      mode: global
    ports:
      - 1936:1936   # haproxy  ui
      - 15672:15672 # rabbitmq ui
    # - 5672:5672   # Do not need to expose amqp
    networks:
      - infra