version: '3.6'
networks:
  infra:
    external: true
services:
  vault1:
    image: vault:1.0.3
    networks:
      - infra
    ports:
      - 8200:8200
    env_file:
      - vault.env
    deploy:
      placement:
        constraints: [node.hostname == $NODE1]
    command: server