version: '3.6'
networks:
  infra:
    external: true
services:
  vault-1:
    image: lysakaleksey/vault-consul:latest
    networks:
      - infra
    ports:
      - 8200:8200
    environment:
      - VAULT_ADDR=$VAULT_ADDR
      - CONSUL_ARGS=$CONSUL_ARGS
      - VAULT_LOCAL_CONFIG=$VAULT_1_CONFIG
      - CONSUL_LOCAL_CONFIG=$CONSUL_LOCAL_CONFIG
    deploy:
      placement:
        constraints:
          - "node.hostname == $NODE1"
  vault-2:
    image: lysakaleksey/vault-consul:latest
    networks:
      - infra
    ports:
      - 8201:8200
    environment:
      - VAULT_ADDR=$VAULT_ADDR
      - CONSUL_ARGS=$CONSUL_ARGS
      - VAULT_LOCAL_CONFIG=$VAULT_2_CONFIG
      - CONSUL_LOCAL_CONFIG=$CONSUL_LOCAL_CONFIG
    deploy:
      placement:
        constraints:
          - "node.hostname == $NODE2"
  vault-3:
    image: lysakaleksey/vault-consul:latest
    networks:
      - infra
    ports:
      - 8202:8200
    environment:
      - VAULT_ADDR=$VAULT_ADDR
      - CONSUL_ARGS=$CONSUL_ARGS
      - VAULT_LOCAL_CONFIG=$VAULT_3_CONFIG
      - CONSUL_LOCAL_CONFIG=$CONSUL_LOCAL_CONFIG
    deploy:
      placement:
        constraints:
          - "node.hostname == $NODE3"
